# Site settings
title: Greg Bernady
email: greg@gbernady.com
description: >
  Hello. I'm Greg. I like creating things, though most of it is purely virtual.
baseurl: ""
url: "https://gbernady.com"
twitter_username: gbernady
github_username:  gbernady
repository: gbernady/gbernady.github.io

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-github-metadata
exclude:
  - Gemfile
  - Gemfile.lock
