# Site settings
title: Greg Bernady
email: greg@gregbernady.com
description: > # this means to ignore newlines until "baseurl:"
  Hello. I'm Greg. I like creating things, though most of it is purely virtual.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gbernady.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gbernady
github_username:  gbernady
repository: gbernady/gbernady.github.io

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-github-metadata
exclude:
  - Gemfile
  - Gemfile.lock
